### ISSUE TITLE
Control Tapo in Cisco network

### ISSUE THREAD

**Issue by helpdeskmast** [bitfocus/companion-module-tplink-taposmartplug#1]
Hi,
I tried the plugin within my home network, wireless connection distributed by my fritzobx and using a MacBook with the latest version of Bitfocus Companion installed without having any kind of problem.
I tried replicating the usage in my company, where we have a wireless infrastructure managed through WLC, but it turns out to be impossible to control the smart plug.
We created an ad hoc VLAN, with internet connection, and at the time of testing on the SSID only a MacBook with the latest version of Bitfocus Companion and Tapo are registered.
We opened a ticket with Cisco, who replied that they do not see any kind of dropped traffic.
Within the bitfocus logs I see the error message "Stopping Update interval due to error."
The connection status remains in "Connecting"

What kind of protocols does the module use to control the smart plug?

Thanks

**Comment by josephdadams** [comment]
It’s HTTP Post, mostly, but looking at the API library, it does need to do an outbound auth depending on device or config. Perhaps that is being blocked?

**Comment by helpdeskmast** [comment]
The Cisco TAC try to collect a new capture, but they found nothing abnormal.
Packets between the PC and the Tapo run smoothly and HTTP Post are visible...

**Comment by helpdeskmast** [comment]
I am very sorry, I had written the wrong TP-Link account email address.
This issue can be closed.
