### ISSUE TITLE
Tapo P100 connection issue with FW 1.2.1

### ISSUE THREAD

**Issue by MathiasGIZ** [bitfocus/companion-module-tplink-taposmartplug#4]
The 16 TP-Link Tapo SmartPlugs in our setup cannot be controlled via Companion any more. After the automatic FW-Upgrade by Tapo, there seems to be a connection issue. The sockets can be switched with the Tapo-App on my iOS Devices, and they have the same IPs.

The last FW is 1.2.1 Build 230804 Rel. 190922

I am trying to rollback to the older FW, but this may be impossible.

**Comment by MathiasGIZ** [comment]
Forgot the model: Tapo P100

**Comment by josephdadams** [comment]
I heard TP-Link was doing this with the Kasa line as well, removing the local LAN control.

**Comment by Ashtlind** [comment]
Facing the same issue here, previously had 4x Tapo P100 up and connected, we believe this was after the recent firmware update of the plugs automatically (lesson learned disabling auto update..). The plugs have updated to v1.2.1

Control of the devices still works in the tapo app but no longer locally.

Current workaround is using IFTTT with a webhook trigger to get up and running in the meantime for a few $ p/m as we rely on these pretty heavy.

Really appreciate this module, great work on it, I hope it ends up being a simple one.

**Comment by josephdadams** [comment]
See this issue: https://github.com/dickydoouk/tp-link-tapo-connect/issues/41

This could be the issue.

It does not look like any updates have occurred in the upstream library we are using for control; it is possible that code author has abandoned the project.

**Comment by sivertbjo** [comment]
Is there a kind soul out there that can continue working with the module? We rely on these to control lighting in our radio studios.

**Comment by josephdadams** [comment]
I’m available for hire to upgrade and fix it. Feel free to email me if you want to discuss that. My email address is on my GitHub profile.

**Comment by dickmann** [comment]
Hi, the module is still not working anymore. I appreciate Joseph´s offer, but it seems there is no business case for anyone to pay you. I still would love to be able to switch my three SmartPlugs with companion instead of using the iphone widget, anyone who is able to support rebuilding this module for "fame only"? Thank you!

**Comment by sivertbjo** [comment]
Solved this by using MQTT and Node-RED: https://flows.nodered.org/node/node-red-contrib-tplink-tapo-connect-api

Set up companion to send "0" or "1" a topic, and subscribed to the topic in Node-RED. Can now control the tapo plugs from stream deck again.

**Comment by josephdadams** [comment]
`v2.0.0` of the module is ready to go and in the betas! This solves the KLAP auth issue.
