### ISSUE TITLE
Tapo P100 connection issue with FW 1.3.0

### ISSUE THREAD

**Issue by roms75** [bitfocus/companion-module-tplink-taposmartplug#5]
Hi, 
There's been an update this last friday on TAPOs P110 and it seems that they reinforced their local communication security.
Since then, the companion module can't connect to the plugs. Is it possible to have an update?
Thx

**Comment by tpk001** [comment]
@josephdadams might be busy.
@istnv would be able to have a look as he recently updated the Kasa plugs module.

**Comment by josephdadams** [comment]
It needs to be converted to v3 api and library updated. Someone is currently running a gofundme in hopes they can raise the funds to hire me to work on it

**Comment by josephdadams** [comment]
`v2.0.0` of the module is ready to go and in the betas!
