### ISSUE TITLE
Feedback is not working.

### ISSUE THREAD

**Issue by MarekPro1** [bitfocus/companion-module-tplink-taposmartplug#9]
Hello feedback doesn't work when i press the button on the outlet the companion doesn't gets any feedback. On version 2.0.1. I am very thankfull that this is going foward I am planing to use it in big.

**Comment by josephdadams** [comment]
Are you able to control the outlet from companion?

**Comment by MarekPro1** [comment]
yes and its working very well. I can send you a video.
